services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: usuarios
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: ./app
    container_name: crud_app
    networks:
      - app_net
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: usuarios
      DB_USER: user
      DB_PASSWORD: pass
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import psycopg2"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:

networks:
  app_net:
    driver: bridge